# Generated by Django 3.2 on 2021-11-21 16:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_name', models.CharField(max_length=255, null=True, unique=True, verbose_name='Наименование')),
                ('storage_address', models.CharField(max_length=1024, null=True, unique=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='StorageUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=64, null=True, verbose_name='Имя пользователя')),
                ('first_name', models.CharField(max_length=256, null=True, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Отчество')),
                ('last_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Фамилия')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон (+код xxx xxx-xx-xx)')),
                ('DUL_series', models.CharField(blank=True, max_length=4, null=True, verbose_name='Серия паспорта')),
                ('DUL_number', models.CharField(blank=True, max_length=6, null=True, verbose_name='Номер паспорта')),
                ('there_is_pd', models.BooleanField(default=False, verbose_name='Есть ли личные данные')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='StoredThing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing_name', models.CharField(max_length=255, null=True, unique=True, verbose_name='Название вещи')),
                ('seasonal', models.BooleanField(default=False, verbose_name='Сезонная вещь')),
                ('tariff1', models.IntegerField(default=0, verbose_name='Цена хранения за неделю/Первый кв. метр')),
                ('tariff2', models.IntegerField(default=0, verbose_name='Цена хранения за месяц/Дельта за следующие кв. метры')),
                ('from_month', models.BooleanField(default=False, verbose_name='Можно хранить меньше месяца')),
            ],
            options={
                'verbose_name': 'Хранимая вещь',
                'verbose_name_plural': 'Хранимые вещи',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(default='1', max_length=100, unique=True, verbose_name='Номер заказа')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата заказа')),
                ('seasonal_store', models.BooleanField(default=False, verbose_name='Сезонные вещи/другое')),
                ('other_type_size', models.IntegerField(default=0, null=True, verbose_name='Габаритность ячейки')),
                ('seasonal_things_count', models.IntegerField(null=True, verbose_name='Количество сезонных вещей')),
                ('store_duration', models.IntegerField(null=True, verbose_name='Длительность хранения')),
                ('store_duration_type', models.CharField(choices=[('0', 'неделя'), ('1', 'месяц')], default='0', max_length=1, verbose_name='Единица длительности хранения')),
                ('summa', models.FloatField(default=0, verbose_name='Стоимость хранения')),
                ('storage', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tgbot.storage', verbose_name='Склад')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tgbot.storedthing', verbose_name='Хранимая вещь')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tgbot.storageuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
